import {NextResponse} from 'next/server';
import {currentUser} from '@/lib/auth';
import {db} from '@/lib/db';
const CANAIS=['MERCADO LIVRE — ABX','MERCADO LIVRE — RWX','MERCADO LIVRE — DANFERX','SHOPEE — ABX','SHOPEE — RWX','SHOPEE — DANFERX','TIKTOK SHOP — ABX'];
const now=()=>new Date().toISOString().slice(0,19);
export async function POST(req:Request){
 const u=await currentUser(); if(!u||u.perfil!=='ADMINISTRADOR') return NextResponse.json({error:'Sem permissão.'},{status:403});
 try{
  const b=await req.json(); const sku=String(b.sku||'').trim().toUpperCase(); const canais:string[]=b.canais||[]; const descricao=String(b.descricao||'').trim(); const titulosML:string[]=(b.titulosML||[]).map((x:any)=>String(x).trim()); const tituloShopee=String(b.tituloShopee||'').trim(); const tituloTiktok=String(b.tituloTiktok||'').trim();
  if(!sku)return NextResponse.json({error:'Informe o SKU.'},{status:400}); if(!canais.length||canais.some(x=>!CANAIS.includes(x)))return NextResponse.json({error:'Selecione pelo menos um canal válido.'},{status:400}); if(!descricao)return NextResponse.json({error:'Preencha a descrição.'},{status:400});
  const temML=canais.some(x=>x.startsWith('MERCADO LIVRE')), temS=canais.some(x=>x.startsWith('SHOPEE')), temT=canais.some(x=>x.startsWith('TIKTOK'));
  if(temML&&(!titulosML.length||titulosML.some(x=>!x)))return NextResponse.json({error:'Preencha todos os títulos do Mercado Livre.'},{status:400}); if(temS&&!tituloShopee)return NextResponse.json({error:'Preencha o título da Shopee.'},{status:400}); if(temT&&!tituloTiktok)return NextResponse.json({error:'Preencha o título do TikTok Shop.'},{status:400});
  const pp=Number(b.precoPremium||0),pc=Number(b.precoClassico||0),ps=Number(b.precoShopee||0),pt=Number(b.precoTiktok||0); if(temML&&pp<=0&&pc<=0)return NextResponse.json({error:'Informe pelo menos um preço do Mercado Livre: Premium ou Clássico.'},{status:400}); if(temS&&ps<=0)return NextResponse.json({error:'Informe o preço da Shopee.'},{status:400}); if(temT&&pt<=0)return NextResponse.json({error:'Informe o preço do TikTok Shop.'},{status:400});
  const c=await db().connect(); try{await c.query('BEGIN'); await c.query(`ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS tipo_origem TEXT DEFAULT 'NOVO'`); await c.query(`ALTER TABLE anuncios ADD COLUMN IF NOT EXISTS observacao_atualizacao TEXT`); const t=now(); await c.query(`INSERT INTO produtos(sku,criado_em,descricao) VALUES($1,$2,$3) ON CONFLICT (sku) DO UPDATE SET descricao=EXCLUDED.descricao`,[sku,t,descricao]); const nr=await c.query('SELECT COALESCE(MAX(numero),0)::int n FROM anuncios WHERE sku=$1',[sku]); let n=nr.rows[0].n;
   for(const canal of canais){n++; const tits=canal.startsWith('MERCADO LIVRE')?titulosML:canal.startsWith('SHOPEE')?[tituloShopee]:[tituloTiktok]; const vals=canal.startsWith('MERCADO LIVRE')?[pp>0?pp:null,pc>0?pc:null,null,null]:canal.startsWith('SHOPEE')?[null,null,ps,null]:[null,null,null,pt]; const r=await c.query(`INSERT INTO anuncios(sku,numero,titulo,descricao,preco,preco_premium,preco_classico,preco_shopee,preco_tiktok,canal,etapa,status,criado_em,atualizado_em,entrada_etapa_em,prioridade,prazo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'FOTO','AGUARDANDO',$11,$11,$11,$12,$13) RETURNING id`,[sku,n,tits[0],descricao,vals[1],vals[0],vals[1],vals[2],vals[3],canal,t,b.prioridade||'NORMAL',b.prazo||null]); const id=r.rows[0].id; for(let i=0;i<tits.length;i++)await c.query('INSERT INTO anuncio_titulos(anuncio_id,ordem,titulo) VALUES($1,$2,$3)',[id,i+1,tits[i]]); await c.query('INSERT INTO historico(anuncio_id,data_hora,etapa,acao,observacao) VALUES($1,$2,$3,$4,$5)',[id,t,'BASE','BASE CONCLUÍDA NO CADASTRO',`${u.nome} | ${canal}`]); await c.query('INSERT INTO historico(anuncio_id,data_hora,etapa,acao,observacao) VALUES($1,$2,$3,$4,$5)',[id,t,'FOTO','TRABALHO RECEBIDO',canal]); }
   await c.query('COMMIT'); return NextResponse.json({ok:true,sku,criados:canais.length});
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }catch(e){console.error(e);return NextResponse.json({error:'Falha ao criar produto/anúncios.'},{status:500})}
}
