"use client";
import Shell from "@/components/Shell"; import {useEffect,useMemo,useState} from "react";
const etapas=['BASE','FOTO','DIMENSÕES','CRIAR ANÚNCIO','PROMOÇÃO','ADS','VÍDEO'];
type T={id:number;sku:string;canal:string;etapa:string;status:string;responsavel?:string;entrada_etapa_em?:string;inicio_etapa_em?:string;prioridade:string;correcao_motivo?:string;tipo_origem?:string;observacao_atualizacao?:string};
type P={id:number;nome:string;perfil:string;etapas:string;concluidos:number;correcoes:number};
type D={metricas:{entraram:number;finalizados:number;correcoes:number};counts:Record<string,number>;trabalhos:T[];responsaveis:Record<string,string[]>;produtividade:P[];periodo:{inicio:string;fim:string}};
function age(v?:string){if(!v)return '—';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));return m<60?`${m} min`:m<1440?`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}min`:`${Math.floor(m/1440)}d ${Math.floor((m%1440)/60)}h`}
export default function Page(){const hoje=new Date().toISOString().slice(0,10);const [d,setD]=useState<D|null>(null),[stage,setStage]=useState<string|null>(null),[msg,setMsg]=useState(''),[inicio,setInicio]=useState(hoje),[fim,setFim]=useState(hoje);const load=()=>fetch(`/api/gestao?inicio=${inicio}&fim=${fim}`).then(r=>r.json()).then(setD);useEffect(()=>{void load()},[]);const items=useMemo(()=>d?.trabalhos.filter(x=>x.etapa===stage)||[],[d,stage]);const act=async(action:string,id:number,destino?:string)=>{if(action==='delete'&&!confirm('Confirma a exclusão definitiva deste anúncio?'))return;const r=await fetch('/api/gestao/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,destino})});const x=await r.json();setMsg(r.ok?'Ação concluída.':x.error||'Erro');if(r.ok)load()};
return <Shell><div className="top noPrint"><div><div className="eyebrow">Controle operacional</div><h1 className="title">Gestão ABX-ON</h1><div className="muted">Acompanhe as etapas, responsáveis e produtividade da equipe.</div></div></div>{msg&&<p className="notice noPrint">{msg}</p>}<div className="grid3 noPrint"><div className="card metric"><span>Entraram hoje</span><b>{d?.metricas.entraram??'—'}</b></div><div className="card metric"><span>Finalizados hoje</span><b>{d?.metricas.finalizados??'—'}</b></div><div className="card metric"><span>Em correção</span><b>{d?.metricas.correcoes??'—'}</b></div></div><section className="section noPrint"><h2>Etapas</h2><div className="gridStages">{etapas.map(e=><button className="card stage stageButton" key={e} onClick={()=>setStage(e)}><strong>{e}</strong><b>{d?.counts?.[e]??0}</b><small>trabalhos ativos</small><div className="stageOwners"><span>Responsável(is)</span><strong>{d?.responsaveis?.[e]?.length?d.responsaveis[e].join(', '):'Não definido'}</strong></div><span className="inspect">VER TRABALHOS →</span></button>)}</div></section>
<section className="section reportArea"><div className="reportHead"><div><div className="eyebrow">Relatório</div><h2>Produtividade por usuário</h2></div><div className="reportFilters noPrint"><label>De <input type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Até <input type="date" value={fim} onChange={e=>setFim(e.target.value)}/></label><button className="btn ghost" onClick={load}>ATUALIZAR</button><button className="btn primary" onClick={()=>window.print()}>IMPRIMIR RELATÓRIO</button></div></div><div className="printOnly reportPrintTitle"><h1>Relatório de produtividade — Esteira ABX-ON</h1><p>Período: {d?.periodo.inicio} a {d?.periodo.fim}</p></div><div className="card tableWrap"><table className="table"><thead><tr><th>Usuário</th><th>Perfil</th><th>Etapas</th><th>Concluídos</th><th>Correções concluídas</th></tr></thead><tbody>{d?.produtividade?.map(p=><tr key={p.id}><td><b>{p.nome}</b></td><td>{p.perfil}</td><td>{p.etapas||'—'}</td><td>{p.concluidos}</td><td>{p.correcoes}</td></tr>)}</tbody></table></div></section>
{stage&&<div className="modalBack noPrint" onClick={()=>setStage(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><div className="eyebrow">Etapa</div><h2>{stage}</h2><p className="muted">Responsável(is): {d?.responsaveis?.[stage]?.join(', ')||'Não definido'}</p></div><button className="x" onClick={()=>setStage(null)}>×</button></div><div className="drawerList">{items.length?items.map(x=><div className="manageWork" key={x.id}><div><span className="tag">{x.status==='CORRIGIR'?'CORREÇÃO':x.prioridade}</span><h3>{x.sku} · {x.canal}</h3><p><b>Processo:</b> {x.status}{x.responsavel?` · ${x.responsavel}`:''}</p><p><b>Tempo na etapa:</b> {age(x.entrada_etapa_em)}</p>{x.observacao_atualizacao&&<p><b>Atualização:</b> {x.observacao_atualizacao}</p>}{x.correcao_motivo&&<p><b>Motivo:</b> {x.correcao_motivo}</p>}</div><div className="manageActions"><select defaultValue="" onChange={e=>{if(e.target.value&&confirm(`Devolver ${x.sku} para ${e.target.value}?`))act('return',x.id,e.target.value);e.currentTarget.value=''}}><option value="" disabled>Devolver para...</option>{etapas.filter(e=>etapas.indexOf(e)<etapas.indexOf(stage)).map(e=><option key={e}>{e}</option>)}</select><button className="btn danger" onClick={()=>act('delete',x.id)}>EXCLUIR</button></div></div>):<div className="empty">Nenhum trabalho nesta etapa.</div>}</div></div></div>}</Shell>}
